#!/usr/bin/env bash
CURRENT_DIR=$(echo $PWD)
cd ~/nixos/
nvim .
for file in $(find . -name "*.nix"); do
	alejandra $file &>/dev/null
done
git diff -U0 *.nix
echo "NixOS Rebuilding..."
sudo nixos-rebuild switch --flake .#desktop &>~/.logs/nixos-rebuild.log || (cat ~/.logs/nixos-rebuild.log | grep --color=error && false)
gen=$(nixos-rebuild list-generations | grep current)
git commit -am "NixOS Rebuild: $gen"
cd $CURRENT_DIR
